POST http://localhost:3333/videos
Content-type: application/json 

{
  "title": "Video node",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/942922cf-8719-49b0-a168-4f161d5be658
Content-type: application/json 

{
  "title": "Video 02",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}

###

DELETE  http://localhost:3333/videos/942922cf-8719-49b0-a168-4f161d5be658